//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебка
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документы
    {
        public int id { get; set; }
        public Nullable<int> id_клиента { get; set; }
        public string Название_документа { get; set; }
        public string Дата_создания { get; set; }
        public string Дата_подписания { get; set; }
        public string Содержание { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
    }
}
